# Generated by Django 6.0 on 2025-12-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifystore',
            old_name='myshopify_domain',
            new_name='shopify_domain',
        ),
    ]
