# Generated by Django 6.0 on 2025-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_myshopify_domain_shopifystore_shopify_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='plan_name',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
