# Generated by Django 6.0 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_shopifystore_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifystore',
            name='plan_name',
            field=models.CharField(choices=[('Free', 'Free Plan'), ('Basic Plan', 'Basic Plan'), ('Premium Plan', 'Premium Plan')], default='Free', max_length=50),
        ),
    ]
