# Generated by Django 6.0 on 2026-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_shopifystore_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifystore',
            name='plan_name',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium')], default='Free', max_length=50),
        ),
    ]
